import { Document } from "langchain/document";
const article1 = [
  new Document({
    pageContent: [
      "Welcome to the 2022-2023 Fantasy Football Season!",
      "",
      "It is our pleasure to introduce to you the Fantasy Pulse Website! Your one stop",
      "destination for all the latest news and headlines across both the",
      "Champions League and Redemption League. Be sure to stop by throughout",
      "the season as we'll be constantly updating with content with plenty of",
      "new features on the way too!",
      "",
      "Furthermore, there have been many other changes that we made this",
      "offseason as well, most notably changing to the Sleeper platform,",
      "which we understand and acknowledge that it might take some time",
      "getting used to.",
      "However, we wholeheartedly believe that Sleeper is a more modern and",
      "innovative fantasy football platform, and it will let our league grow",
      "and become more immersive than ever! By utilizing the Sleeper API, we",
      "were able to smoothly integrate the league onto the website and make",
      "the league even more interactive!",
      "I’d like to thank everyone that has helped along the way. It really",
      "was a team effort and we sincerely appreciate everyone's hard work and",
      "feedback as we strive to make this league better than ever.",
      "",
      "Thank you everyone, Truly.",
    ],
    metadata: {
      title: "Welcome to the 2022-2023 Fantasy Football Season!",
      author: "Fantasy Pulse Editorial Team",
      date: "Sep 1, 2022",
    },
  }),
];

const article2 = [
  new Document({
    pageContent: [
      "The face that scares a lot of people in this league...",
      "",
      "The Sunday night thriller that was bound to cause NIGHTMARES for weeks",
      "if not months to come. A man wearing a mask was seen fleeing the scene",
      "leaving behind a deflated FG in the second round of the playoffs.",
      "",
      "Imran narrowly creeped by FG by a margin of .04 points (!!!) led by a",
      "garbage time surge from Scarry Terry. How did that happen, one might",
      "wonder? In order to answer that, we must go back a couple of weeks to",
      "see how it all began.",
      "",
      '"We weren\'t supposed to be here..."',
      "",
      'Imran said in an interview with our Fantasy Pulse reporters, "We literally got',
      'into the playoffs with a loss", referring to his 7-7 regular season',
      "finish to secure the final spot in the Champions League playoffs.",
      "Every matchup he went into, he was the underdog. Every start he made,",
      "was met with criticism and mockery. No one believed he would win a",
      "game, yet alone multiple.",
      "",
      "However, calling Imran's historic title run a miracle would be a",
      "detriment to his gutsy plays and coaching decisions he's made",
      "throughout the playoffs. From starting Rex Burkhead to feeding the",
      "hothand in Rashaad Penny, Imran galvanized his team and said all the",
      "right things in the lockerroom to give his team the morale boost they",
      "needed to keep going.",
      "",
      "In a run that included defeating multiple powerhouses and previous",
      "champions, Imran will look to continue that momentum in what is sure",
      "to be a monstrous title defense. Although he might not have his guys",
      "from last year with him, Imran has shown time and time again that he's",
      "able to find the diamonds in the rough and has already proven that he",
      "could win with a chip on his shoulder, now let's see if he can win",
      "with the chip in his hands.",
    ],
    metadata: {
      title: "The Face that Scares: Imran's Championship Run",
      author: "Fantasy Pulse Editorial Team",
      date: "Dec 15, 2022",
    },
  }),
];

const article3 = [
  new Document({
    pageContent: [
      "As we kickoff the new fantasy season, let's take a look at this year's newcomers!",
      "",
      "One and done... Edo and Khader bounced back IMMEDIATELY after only",
      "spending a total of one season in the Redemption League. Their short",
      "tenure sparked some controversy however, raising questions about the",
      "potential glaring difference in competition between both leagues, as",
      "they dominated their way through the regular season, clinching the #1",
      "and #2 seeds respectively.",
      "",
      "With a second chance at glory and newfound confidence, Edo and Khader",
      "are eager to silence the critics and dominate in the Champions League",
      "this season. And now that their losing days are behind them, the",
      "league better be weary...",
      "",
      "With all the media and hype surrounding Edo and Khader, we can't",
      "forget about the two guys that BEAT THEM in the Redemption League",
      "playoffs last year!",
      "",
      "Former Redemption League veteran YSL, who denounced the title of the",
      "longest tenured Redemption League member*, finally clinched that",
      "elusive ticket to the Champions League that he has sought after for so",
      "long. YSL will be punching above his weight class as he draws a tough",
      "matchup week 1, facing the defending champ Imran himself, and will",
      "look to put all his experiences slugging it out in RL to the test,",
      'Vegas has him as a 76 point underdog with a "puncher\'s chance".',
      "",
      "Besting YSL in the RL title game, Reigning Redemption League Champion",
      "King K0bra stormed through the competition during his dominant",
      "post-season performance to cement his place in the Champions League.",
      "King K0bra ensured our reporters that his winning formula will indeed",
      "translate well into the big leagues. When asked about his message to",
      'his fellow fantasy managers, King K0bra said "The real fantasy champ',
      "is here. I'm going back to back like I'm Jordan 96-97, both RL and CL",
      'titles in hand, what do you call that? A double crown?" ....well his',
      "head is definitely big enough to wear a double crown that's for sure.",
      "",
      "Sharpened by the harsh conditions in the Redemption League, both YSL",
      "and King K0bra will look to claw their way to the top of the league",
      "and establish themselves as a force to be reckoned with.",
      "",
      "*The title now belongs to Unc, as it'll be his 5th year in the",
      "Redemption League if he doesn't qualify this season, breaking YSL's",
      "previous league record of 4 years.",
    ],
    metadata: {
      title: "Newcomers and Redemption League Veterans: A Season of Change",
      author: "Fantasy Pulse Editorial Team",
      date: "Oct 10, 2022",
    },
  }),
];

const article4 = [
  new Document({
    pageContent: [
      "Everyone’s favorite legend might be on the move soon! Along with many other familiar faces.",
      "According to a source close to Ganay’s camp, the organization is heavily involved in trade talks and are “Trying to get him shipped” to the highest bidder. Barring any unexpected buffs, the Harris Valley hero might be a tough sell due to his recent performances, but Ganay is sure that the change of scenery will help him play up to his potential.",
      "Tensions are at an all-time high between King K0bra and akhjefe as the two had to get physically separated after Sunday’s slate of games. “He’s gonna have something coming for him alright” JEFE told our reporters following Monday’s practice report, “He’s not even gonna know what hit him”. King K0bra has been on the fortunate side of Tua’s showing last week as he cruised to a convincing 2-0 start, when asked about the inevitable attention that comes with his recent wins King K0bra had this to say:",
      "“Winning ain't easy, I just make it look easy… That fraud akhjefe can only wish to emulate my success, he tried mirroring me and where did that take him, exactly where he belongs. 0-2 carry the **** on”",
      ,
    ],
    metadata: {
      title: "NEWCASTLE",
      author: "Mahad Fahiye",
      jobTitle: "RCL Staff Writer",
      date: "Sep 19, 2022",
    },
  }),
];

export const articles = {
  article1,
  article2,
  article3,
  article4,
  // You can add more articles here as needed
};
